__title__ = 'autocorrect'
__description__ = 'Autocorrection package for English.'
__url__ = ''
__version__ = '0.1.0'
__build__ = 0x0010
__author__ = 'Ashwin Revo'
__author_email__ = 'noemail@example.com'
__license__ = 'Apache 2.0'
__copyright__ = 'Copyright 2020'
